version: '3.8'

services:
  psmusic-server:
    container_name: psmusic-server
    build:
      context: ./PSMusic.Server
      dockerfile: Dockerfile
    ports:
      - "7215:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DBConnection=${DB_CONNECTION}
      - Elasticsearch__Uri=${ELASTICSEARCH_URI}
      - Elasticsearch__DefaultIndex=${ELASTICSEARCH_DEFAULTINDEX}
      - Elasticsearch__ApiKey=${ELASTICSEARCH_APIKEY}
      - Jwt__Key=HongNamEntertainmentSuperSecretKeyyyyyyyy666
      - Jwt__Issuer=PSMusic
      - Jwt__Audience=PSMusicUsers
      - Jwt__ExpiryMinutes=60
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env

  psmusic-client:
    container_name: psmusic-client
    build:
      context: ./psmusic.client
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:7215/api
    ports:
      - "5173:80"
    depends_on:
      - psmusic-server
    restart: unless-stopped
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge
