version: '3.8'

services:
  nginx-gateway:
    container_name: nginx-gateway
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - psmusic-server
      - psmusic-client
    restart: always
    networks:
      - app-network

  psmusic-server:
    container_name: psmusic-server
    build:
      context: ./PSMusic.Server
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DBConnection=${DB_CONNECTION}
      - Jwt__Key=HongNamEntertainmentSuperSecretKeyyyyyyyy666
      - Jwt__Issuer=PSMusic
      - Jwt__Audience=PSMusicUsers
      - Jwt__ExpiryMinutes=60
    restart: always
    networks:
      - app-network
    env_file:
      - .env

  psmusic-client:
    container_name: psmusic-client
    build:
      context: ./psmusic.client
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - psmusic-server
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge